# Generated by Django 4.1.2 on 2023-01-29 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(blank=True, default='{{user}}', max_length=25, null=True, verbose_name='管理者名')),
                ('class_name', models.CharField(blank=True, max_length=23, null=True, verbose_name='Class名')),
                ('backimage', models.ImageField(upload_to='media/', verbose_name='BackImage')),
                ('explain', models.TextField(blank=True, max_length=180, verbose_name='explain')),
            ],
            options={
                'verbose_name_plural': 'ClassName',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infomation', models.TextField(blank=True, max_length=180, verbose_name='infomation')),
                ('hobby', models.CharField(choices=[('TV', 'TV'), ('読書', '読書'), ('ゲーム', 'ゲーム'), ('PC', 'PC'), ('映画', '映画'), ('プログラミング', 'プログラミング'), ('VR/AR', 'VR/AR'), ('運動', '運動')], max_length=8)),
                ('detail', models.CharField(choices=[('大学生', '大学生'), ('サイト', 'サイト'), ('社会人', '社会人'), ('会社', '会社'), ('小学生', '小学生'), ('学校', '学校'), ('中学生', '中学生'), ('高校生', '高校生')], max_length=8)),
                ('explain', models.TextField(blank=True, max_length=180, verbose_name='explain')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Account',
            },
        ),
    ]
