# Generated by Django 4.1.2 on 2023-02-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('会社', '会社'), ('中学生', '中学生'), ('学校', '学校'), ('小学生', '小学生'), ('社会人', '社会人'), ('高校生', '高校生'), ('サイト', 'サイト'), ('大学生', '大学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('ゲーム', 'ゲーム'), ('PC', 'PC'), ('VR/AR', 'VR/AR'), ('TV', 'TV'), ('プログラミング', 'プログラミング'), ('読書', '読書'), ('運動', '運動'), ('映画', '映画')], max_length=8),
        ),
    ]
