# Generated by Django 4.1.2 on 2023-02-26 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XLiNK', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connection',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='followers',
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('サイト', 'サイト'), ('小学生', '小学生'), ('中学生', '中学生'), ('大学生', '大学生'), ('学校', '学校'), ('会社', '会社'), ('高校生', '高校生'), ('社会人', '社会人')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('読書', '読書'), ('VR/AR', 'VR/AR'), ('TV', 'TV'), ('運動', '運動'), ('PC', 'PC'), ('プログラミング', 'プログラミング'), ('ゲーム', 'ゲーム'), ('映画', '映画')], max_length=8),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=180, verbose_name='comment'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
