# Generated by Django 4.1.2 on 2023-02-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('学校', '学校'), ('中学生', '中学生'), ('会社', '会社'), ('高校生', '高校生'), ('大学生', '大学生'), ('サイト', 'サイト'), ('社会人', '社会人'), ('小学生', '小学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('読書', '読書'), ('プログラミング', 'プログラミング'), ('VR/AR', 'VR/AR'), ('映画', '映画'), ('PC', 'PC'), ('TV', 'TV'), ('ゲーム', 'ゲーム'), ('運動', '運動')], max_length=8),
        ),
    ]
