# Generated by Django 4.1.2 on 2023-02-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0002_rename_genre_group_category_alter_account_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('中学生', '中学生'), ('高校生', '高校生'), ('大学生', '大学生'), ('社会人', '社会人'), ('サイト', 'サイト'), ('小学生', '小学生'), ('学校', '学校'), ('会社', '会社')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('読書', '読書'), ('映画', '映画'), ('運動', '運動'), ('VR/AR', 'VR/AR'), ('TV', 'TV'), ('ゲーム', 'ゲーム'), ('プログラミング', 'プログラミング'), ('PC', 'PC')], max_length=8),
        ),
    ]
