# Generated by Django 4.1.2 on 2023-02-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0002_alter_account_detail_alter_account_hobby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='class_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('会社', '会社'), ('サイト', 'サイト'), ('小学生', '小学生'), ('高校生', '高校生'), ('社会人', '社会人'), ('大学生', '大学生'), ('学校', '学校'), ('中学生', '中学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('PC', 'PC'), ('プログラミング', 'プログラミング'), ('ゲーム', 'ゲーム'), ('読書', '読書'), ('VR/AR', 'VR/AR'), ('映画', '映画'), ('TV', 'TV'), ('運動', '運動')], max_length=8),
        ),
    ]
