# Generated by Django 4.1.2 on 2023-02-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0002_rename_connection_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('会社', '会社'), ('社会人', '社会人'), ('中学生', '中学生'), ('小学生', '小学生'), ('サイト', 'サイト'), ('高校生', '高校生'), ('大学生', '大学生'), ('学校', '学校')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('ゲーム', 'ゲーム'), ('VR/AR', 'VR/AR'), ('TV', 'TV'), ('運動', '運動'), ('映画', '映画'), ('読書', '読書'), ('プログラミング', 'プログラミング'), ('PC', 'PC')], max_length=8),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
