# Generated by Django 4.1.2 on 2023-02-25 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0002_alter_account_detail_alter_account_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('小学生', '小学生'), ('大学生', '大学生'), ('サイト', 'サイト'), ('中学生', '中学生'), ('社会人', '社会人'), ('会社', '会社'), ('学校', '学校'), ('高校生', '高校生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('VR/AR', 'VR/AR'), ('TV', 'TV'), ('読書', '読書'), ('映画', '映画'), ('PC', 'PC'), ('プログラミング', 'プログラミング'), ('運動', '運動'), ('ゲーム', 'ゲーム')], max_length=8),
        ),
        migrations.AlterField(
            model_name='comment',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='XLiNK.group', to_field='name'),
        ),
    ]
