# Generated by Django 4.1.2 on 2023-01-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0003_alter_account_detail_alter_account_hobby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('小学生', '小学生'), ('社会人', '社会人'), ('学校', '学校'), ('サイト', 'サイト'), ('会社', '会社'), ('高校生', '高校生'), ('中学生', '中学生'), ('大学生', '大学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('VR/AR', 'VR/AR'), ('TV', 'TV'), ('読書', '読書'), ('運動', '運動'), ('ゲーム', 'ゲーム'), ('PC', 'PC'), ('プログラミング', 'プログラミング'), ('映画', '映画')], max_length=8),
        ),
    ]
