# Generated by Django 4.1.2 on 2023-02-25 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XLiNK', '0003_alter_account_detail_alter_account_hobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('社会人', '社会人'), ('高校生', '高校生'), ('会社', '会社'), ('学校', '学校'), ('小学生', '小学生'), ('中学生', '中学生'), ('大学生', '大学生'), ('サイト', 'サイト')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('ゲーム', 'ゲーム'), ('運動', '運動'), ('プログラミング', 'プログラミング'), ('読書', '読書'), ('PC', 'PC'), ('VR/AR', 'VR/AR'), ('TV', 'TV'), ('映画', '映画')], max_length=8),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
