# Generated by Django 4.1.2 on 2023-02-14 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0003_rename_comment_comment_text_alter_account_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('社会人', '社会人'), ('中学生', '中学生'), ('学校', '学校'), ('会社', '会社'), ('大学生', '大学生'), ('小学生', '小学生'), ('サイト', 'サイト'), ('高校生', '高校生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('TV', 'TV'), ('読書', '読書'), ('プログラミング', 'プログラミング'), ('ゲーム', 'ゲーム'), ('PC', 'PC'), ('運動', '運動'), ('映画', '映画'), ('VR/AR', 'VR/AR')], max_length=8),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='XLiNK.group', verbose_name='投稿先'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=180, verbose_name='コメント'),
        ),
    ]
