# Generated by Django 4.1.2 on 2023-02-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0003_rename_class_name_group_name_alter_account_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('高校生', '高校生'), ('学校', '学校'), ('中学生', '中学生'), ('社会人', '社会人'), ('会社', '会社'), ('大学生', '大学生'), ('小学生', '小学生'), ('サイト', 'サイト')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('TV', 'TV'), ('ゲーム', 'ゲーム'), ('運動', '運動'), ('読書', '読書'), ('映画', '映画'), ('PC', 'PC'), ('VR/AR', 'VR/AR'), ('プログラミング', 'プログラミング')], max_length=8),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.SlugField(blank=True, max_length=23, null=True, verbose_name='Class名'),
        ),
    ]
