# Generated by Django 4.1.2 on 2023-02-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0003_alter_account_detail_alter_account_hobby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=10000)),
                ('user', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('大学生', '大学生'), ('高校生', '高校生'), ('会社', '会社'), ('中学生', '中学生'), ('小学生', '小学生'), ('サイト', 'サイト'), ('社会人', '社会人'), ('学校', '学校')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('プログラミング', 'プログラミング'), ('運動', '運動'), ('VR/AR', 'VR/AR'), ('映画', '映画'), ('TV', 'TV'), ('ゲーム', 'ゲーム'), ('読書', '読書'), ('PC', 'PC')], max_length=8),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
