# Generated by Django 4.1.2 on 2023-02-25 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XLiNK', '0004_alter_account_detail_alter_account_hobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('大学生', '大学生'), ('サイト', 'サイト'), ('社会人', '社会人'), ('小学生', '小学生'), ('会社', '会社'), ('中学生', '中学生'), ('高校生', '高校生'), ('学校', '学校')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('TV', 'TV'), ('映画', '映画'), ('VR/AR', 'VR/AR'), ('ゲーム', 'ゲーム'), ('PC', 'PC'), ('読書', '読書'), ('運動', '運動'), ('プログラミング', 'プログラミング')], max_length=8),
        ),
        migrations.AlterField(
            model_name='comment',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='XLiNK.group'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
