# Generated by Django 4.1.2 on 2023-02-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0005_alter_account_detail_alter_account_hobby_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveConstraint(
            model_name='group',
            name='group',
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('大学生', '大学生'), ('中学生', '中学生'), ('サイト', 'サイト'), ('社会人', '社会人'), ('学校', '学校'), ('小学生', '小学生'), ('会社', '会社'), ('高校生', '高校生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('TV', 'TV'), ('PC', 'PC'), ('VR/AR', 'VR/AR'), ('プログラミング', 'プログラミング'), ('運動', '運動'), ('映画', '映画'), ('ゲーム', 'ゲーム'), ('読書', '読書')], max_length=8),
        ),
    ]
