# Generated by Django 4.1.2 on 2023-02-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0005_alter_account_detail_alter_account_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('学校', '学校'), ('会社', '会社'), ('サイト', 'サイト'), ('社会人', '社会人'), ('小学生', '小学生'), ('高校生', '高校生'), ('中学生', '中学生'), ('大学生', '大学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('読書', '読書'), ('ゲーム', 'ゲーム'), ('PC', 'PC'), ('VR/AR', 'VR/AR'), ('TV', 'TV'), ('運動', '運動'), ('映画', '映画'), ('プログラミング', 'プログラミング')], max_length=8),
        ),
    ]
