# Generated by Django 4.1.2 on 2023-02-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0005_alter_account_detail_alter_account_hobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('高校生', '高校生'), ('学校', '学校'), ('社会人', '社会人'), ('小学生', '小学生'), ('サイト', 'サイト'), ('中学生', '中学生'), ('会社', '会社'), ('大学生', '大学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('運動', '運動'), ('VR/AR', 'VR/AR'), ('映画', '映画'), ('ゲーム', 'ゲーム'), ('TV', 'TV'), ('PC', 'PC'), ('読書', '読書'), ('プログラミング', 'プログラミング')], max_length=8),
        ),
    ]
