# Generated by Django 4.1.2 on 2023-01-31 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XLiNK', '0005_group_genre_alter_account_detail_alter_account_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('小学生', '小学生'), ('会社', '会社'), ('社会人', '社会人'), ('サイト', 'サイト'), ('大学生', '大学生'), ('高校生', '高校生'), ('学校', '学校'), ('中学生', '中学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('映画', '映画'), ('プログラミング', 'プログラミング'), ('VR/AR', 'VR/AR'), ('TV', 'TV'), ('運動', '運動'), ('ゲーム', 'ゲーム'), ('PC', 'PC'), ('読書', '読書')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.OneToOneField(default='{{user.-id}}', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='genre',
            field=models.CharField(choices=[('運動', '運動'), ('芸術', '芸術'), ('科学', '科学'), ('企業', '企業'), ('音楽', '音楽'), ('経済', '経済'), ('投資', '投資')], max_length=8),
        ),
    ]
