# Generated by Django 4.1.2 on 2023-02-26 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XLiNK', '0006_remove_comment_comment_remove_group_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('高校生', '高校生'), ('社会人', '社会人'), ('会社', '会社'), ('学校', '学校'), ('大学生', '大学生'), ('小学生', '小学生'), ('サイト', 'サイト'), ('中学生', '中学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('読書', '読書'), ('映画', '映画'), ('VR/AR', 'VR/AR'), ('PC', 'PC'), ('TV', 'TV'), ('ゲーム', 'ゲーム'), ('プログラミング', 'プログラミング'), ('運動', '運動')], max_length=8),
        ),
        migrations.AlterField(
            model_name='group',
            name='manager_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='管理者名'),
        ),
    ]
