# Generated by Django 4.1.2 on 2023-02-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0006_alter_account_detail_alter_account_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('大学生', '大学生'), ('小学生', '小学生'), ('社会人', '社会人'), ('中学生', '中学生'), ('会社', '会社'), ('高校生', '高校生'), ('学校', '学校'), ('サイト', 'サイト')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('映画', '映画'), ('PC', 'PC'), ('ゲーム', 'ゲーム'), ('運動', '運動'), ('VR/AR', 'VR/AR'), ('プログラミング', 'プログラミング'), ('読書', '読書'), ('TV', 'TV')], max_length=8),
        ),
    ]
