# Generated by Django 4.1.2 on 2023-01-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0007_alter_account_options_alter_account_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('中学生', '中学生'), ('学校', '学校'), ('会社', '会社'), ('大学生', '大学生'), ('小学生', '小学生'), ('サイト', 'サイト'), ('社会人', '社会人'), ('高校生', '高校生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('PC', 'PC'), ('運動', '運動'), ('読書', '読書'), ('映画', '映画'), ('TV', 'TV'), ('VR/AR', 'VR/AR'), ('ゲーム', 'ゲーム'), ('プログラミング', 'プログラミング')], max_length=8),
        ),
        migrations.AlterField(
            model_name='group',
            name='genre',
            field=models.CharField(choices=[('科学', '科学'), ('音楽', '音楽'), ('経済', '経済'), ('芸術', '芸術'), ('投資', '投資'), ('運動', '運動'), ('企業', '企業')], max_length=8),
        ),
    ]
