# Generated by Django 4.1.2 on 2023-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0007_alter_account_detail_alter_account_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('会社', '会社'), ('中学生', '中学生'), ('社会人', '社会人'), ('サイト', 'サイト'), ('小学生', '小学生'), ('高校生', '高校生'), ('学校', '学校'), ('大学生', '大学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('映画', '映画'), ('TV', 'TV'), ('運動', '運動'), ('読書', '読書'), ('ゲーム', 'ゲーム'), ('VR/AR', 'VR/AR'), ('PC', 'PC'), ('プログラミング', 'プログラミング')], max_length=8),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.SlugField(blank=True, max_length=23, null=True, verbose_name='Class名'),
        ),
    ]
