# Generated by Django 4.1.2 on 2023-02-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0007_alter_account_detail_alter_account_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('サイト', 'サイト'), ('社会人', '社会人'), ('小学生', '小学生'), ('大学生', '大学生'), ('中学生', '中学生'), ('学校', '学校'), ('会社', '会社'), ('高校生', '高校生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('ゲーム', 'ゲーム'), ('プログラミング', 'プログラミング'), ('映画', '映画'), ('PC', 'PC'), ('VR/AR', 'VR/AR'), ('運動', '運動'), ('読書', '読書'), ('TV', 'TV')], max_length=8),
        ),
    ]
