# Generated by Django 4.1.2 on 2023-02-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0008_alter_account_detail_alter_account_hobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('学校', '学校'), ('中学生', '中学生'), ('サイト', 'サイト'), ('小学生', '小学生'), ('社会人', '社会人'), ('会社', '会社'), ('大学生', '大学生'), ('高校生', '高校生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('ゲーム', 'ゲーム'), ('プログラミング', 'プログラミング'), ('PC', 'PC'), ('VR/AR', 'VR/AR'), ('映画', '映画'), ('読書', '読書'), ('運動', '運動'), ('TV', 'TV')], max_length=8),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=23, null=True, verbose_name='Class名'),
        ),
    ]
