# Generated by Django 4.1.2 on 2023-01-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0009_alter_account_detail_alter_account_hobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('大学生', '大学生'), ('社会人', '社会人'), ('小学生', '小学生'), ('高校生', '高校生'), ('中学生', '中学生'), ('学校', '学校'), ('会社', '会社'), ('サイト', 'サイト')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('映画', '映画'), ('プログラミング', 'プログラミング'), ('VR/AR', 'VR/AR'), ('ゲーム', 'ゲーム'), ('TV', 'TV'), ('運動', '運動'), ('読書', '読書'), ('PC', 'PC')], max_length=8),
        ),
        migrations.AlterField(
            model_name='group',
            name='genre',
            field=models.CharField(choices=[('運動', '運動'), ('経済', '経済'), ('企業', '企業'), ('音楽', '音楽'), ('投資', '投資'), ('科学', '科学'), ('芸術', '芸術')], max_length=8),
        ),
    ]
