# Generated by Django 4.1.2 on 2023-02-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0009_alter_account_detail_alter_account_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('大学生', '大学生'), ('学校', '学校'), ('高校生', '高校生'), ('会社', '会社'), ('中学生', '中学生'), ('小学生', '小学生'), ('社会人', '社会人'), ('サイト', 'サイト')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('PC', 'PC'), ('読書', '読書'), ('映画', '映画'), ('運動', '運動'), ('プログラミング', 'プログラミング'), ('VR/AR', 'VR/AR'), ('TV', 'TV'), ('ゲーム', 'ゲーム')], max_length=8),
        ),
    ]
