# Generated by Django 4.1.2 on 2023-02-03 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XLiNK', '0010_alter_account_detail_alter_account_hobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('高校生', '高校生'), ('サイト', 'サイト'), ('学校', '学校'), ('社会人', '社会人'), ('小学生', '小学生'), ('中学生', '中学生'), ('大学生', '大学生'), ('会社', '会社')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('運動', '運動'), ('読書', '読書'), ('PC', 'PC'), ('プログラミング', 'プログラミング'), ('映画', '映画'), ('ゲーム', 'ゲーム'), ('VR/AR', 'VR/AR'), ('TV', 'TV')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.OneToOneField(default='{{-User}}', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='genre',
            field=models.CharField(choices=[('科学', '科学'), ('投資', '投資'), ('経済', '経済'), ('企業', '企業'), ('音楽', '音楽'), ('運動', '運動'), ('TalkClass', 'TalkClass'), ('芸術', '芸術')], max_length=9),
        ),
        migrations.AlterField(
            model_name='group',
            name='manager_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='管理者名'),
        ),
    ]
