# Generated by Django 4.1.2 on 2023-02-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0010_alter_account_detail_alter_account_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('小学生', '小学生'), ('会社', '会社'), ('学校', '学校'), ('社会人', '社会人'), ('大学生', '大学生'), ('サイト', 'サイト'), ('中学生', '中学生'), ('高校生', '高校生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('読書', '読書'), ('PC', 'PC'), ('運動', '運動'), ('映画', '映画'), ('VR/AR', 'VR/AR'), ('プログラミング', 'プログラミング'), ('ゲーム', 'ゲーム'), ('TV', 'TV')], max_length=8),
        ),
    ]
