# Generated by Django 4.1.2 on 2023-02-03 22:24

import XLiNK.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0011_alter_account_detail_alter_account_hobby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(XLiNK.models.Account, XLiNK.models.Account)], max_length=9)),
                ('text', models.TextField(blank=True, max_length=180)),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('サイト', 'サイト'), ('大学生', '大学生'), ('小学生', '小学生'), ('中学生', '中学生'), ('高校生', '高校生'), ('学校', '学校'), ('社会人', '社会人'), ('会社', '会社')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('ゲーム', 'ゲーム'), ('VR/AR', 'VR/AR'), ('運動', '運動'), ('読書', '読書'), ('TV', 'TV'), ('プログラミング', 'プログラミング'), ('映画', '映画'), ('PC', 'PC')], max_length=8),
        ),
        migrations.AlterField(
            model_name='group',
            name='genre',
            field=models.CharField(choices=[('TalkClass', 'TalkClass'), ('音楽', '音楽'), ('企業', '企業'), ('経済', '経済'), ('運動', '運動'), ('科学', '科学'), ('芸術', '芸術'), ('投資', '投資')], max_length=9),
        ),
    ]
