# Generated by Django 4.1.2 on 2023-02-04 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XLiNK', '0012_comment_alter_account_detail_alter_account_hobby_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comment'},
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('サイト', 'サイト'), ('中学生', '中学生'), ('高校生', '高校生'), ('小学生', '小学生'), ('学校', '学校'), ('大学生', '大学生'), ('会社', '会社'), ('社会人', '社会人')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('ゲーム', 'ゲーム'), ('VR/AR', 'VR/AR'), ('PC', 'PC'), ('運動', '運動'), ('映画', '映画'), ('プログラミング', 'プログラミング'), ('読書', '読書'), ('TV', 'TV')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='XLiNK.account'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='group',
            name='genre',
            field=models.CharField(choices=[('経済', '経済'), ('科学', '科学'), ('運動', '運動'), ('音楽', '音楽'), ('TalkClass', 'TalkClass'), ('芸術', '芸術'), ('企業', '企業'), ('投資', '投資')], max_length=9),
        ),
    ]
