# Generated by Django 4.1.2 on 2023-02-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0013_alter_comment_options_alter_account_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('学校', '学校'), ('社会人', '社会人'), ('中学生', '中学生'), ('大学生', '大学生'), ('高校生', '高校生'), ('サイト', 'サイト'), ('会社', '会社'), ('小学生', '小学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('ゲーム', 'ゲーム'), ('プログラミング', 'プログラミング'), ('TV', 'TV'), ('VR/AR', 'VR/AR'), ('読書', '読書'), ('PC', 'PC'), ('映画', '映画'), ('運動', '運動')], max_length=8),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='group',
            name='genre',
            field=models.CharField(choices=[('TalkClass', 'TalkClass'), ('科学', '科学'), ('経済', '経済'), ('音楽', '音楽'), ('企業', '企業'), ('運動', '運動'), ('芸術', '芸術'), ('投資', '投資')], max_length=9),
        ),
    ]
