# Generated by Django 4.1.2 on 2023-02-07 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XLiNK', '0014_remove_comment_name_alter_account_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='XLiNK.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('社会人', '社会人'), ('小学生', '小学生'), ('学校', '学校'), ('サイト', 'サイト'), ('中学生', '中学生'), ('大学生', '大学生'), ('会社', '会社'), ('高校生', '高校生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('VR/AR', 'VR/AR'), ('PC', 'PC'), ('プログラミング', 'プログラミング'), ('ゲーム', 'ゲーム'), ('運動', '運動'), ('映画', '映画'), ('読書', '読書'), ('TV', 'TV')], max_length=8),
        ),
        migrations.AlterField(
            model_name='group',
            name='genre',
            field=models.CharField(choices=[('芸術', '芸術'), ('投資', '投資'), ('科学', '科学'), ('音楽', '音楽'), ('経済', '経済'), ('運動', '運動'), ('TalkClass', 'TalkClass'), ('企業', '企業')], max_length=9),
        ),
    ]
